--PART A
--1
SELECT PERSON.PERSONNAME,DEPT.DEPARTMENTNAME,DEPT.DEPARTMENTCODE
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID;

--2
SELECT PERSON.PERSONNAME,DEPT.DEPARTMENTNAME
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
WHERE DEPT.LOCATION='C-BLOCK';

--3
SELECT PERSON.PERSONNAME,PERSON.SALARY,DEPT.DEPARTMENTNAME
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
WHERE CITY='JAMNAGAR';

--4
SELECT PERSON.PERSONNAME,PERSON.SALARY,DEPT.DEPARTMENTNAME
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
WHERE PERSON.CITY<>'RAJKOT';

--5
SELECT PERSON.PERSONNAME,DEPT.DEPARTMENTNAME
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
WHERE DEPT.DEPARTMENTNAME='CIVIL' AND JOININGDATE>'01-08-2001';

--6
SELECT PERSON.PERSONNAME,DEPT.DEPARTMENTNAME
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
WHERE DEPT.DEPARTMENTNAME='COMPUTER';

--7


--8
SELECT DEPT.DEPARTMENTNAME,COUNT(PERSON.PERSONNAME) AS TOTAL_NUMBER
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
GROUP BY DEPT.DEPARTMENTNAME;

--9
SELECT DEPT.DEPARTMENTNAME,MIN(PERSON.SALARY) AS MIN_SALARY,MAX(PERSON.SALARY) AS MAX_SALARY
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
GROUP BY DEPT.DEPARTMENTNAME;

--10
SELECT PERSON.CITY,SUM(PERSON.SALARY) AS TOTAL_SALARY,MIN(PERSON.SALARY) AS MIN_SALARY,MAX(PERSON.SALARY) AS MAX_SALARY,AVG(PERSON.SALARY) AS AVG_SALARY
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
GROUP BY PERSON.CITY;

--11
SELECT DEPT.DEPARTMENTNAME,AVG(PERSON.SALARY) AS AVG_SALARY
FROM PERSON JOIN DEPT
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
WHERE PERSON.CITY='AHMEDABAD'
GROUP BY DEPT.DEPARTMENTNAME;

--12


--PART B
--1
