CREATE TABLE SALES_DATA
( REGION VARCHAR(50),
 PRODUCT VARCHAR(20),
 SALES_AMOUNT INT,
 YEAR INT);

INSERT INTO SALES_DATA VALUES('NORTH AMERICA','WATCH',1500,2023)
INSERT INTO SALES_DATA VALUES('EUROPE','MOBILE',1200,2023)
INSERT INTO SALES_DATA VALUES('ASIA','WATCH',1800,2023)
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','TV',900,2024)
INSERT INTO SALES_DATA VALUES('EUROPE','WATCH',2000,2024)
INSERT INTO SALES_DATA VALUES('ASIA','MOBILE',1000,2024)
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','MOBILE',1600,2023)
INSERT INTO SALES_DATA VALUES('EUROPE','TV',1500,2023)
INSERT INTO SALES_DATA VALUES('ASIA','TV',1100,2024)
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','WATCH',1700,2024)

SELECT * FROM SALES_DATA;

--PART-A
--1
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT FROM SALES_DATA GROUP BY REGION;
--2
SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVG_SALES_AMOUNT FROM SALES_DATA GROUP BY PRODUCT;
--3
SELECT YEAR,MAX(SALES_AMOUNT) AS MAX_SALES_AMOUNT FROM SALES_DATA GROUP BY YEAR;
--4
SELECT REGION,YEAR,MIN(SALES_AMOUNT) AS MAX_SALES_AMOUNT FROM SALES_DATA GROUP BY YEAR,REGION;
--5
SELECT REGION,COUNT(PRODUCT) AS COUNT_PRODUCT FROM SALES_DATA GROUP BY REGION;
--6
SELECT YEAR,PRODUCT,SUM(SALES_AMOUNT) AS SALES_AMOUNT FROM SALES_DATA GROUP BY YEAR,PRODUCT;
--7
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA GROUP BY REGION HAVING SUM(SALES_AMOUNT)>5000;
--8
