CREATE TABLE STU_INFO
(RNO INT,
 NAME VARCHAR(20),
 BRANCH VARCHAR(10));

INSERT INTO STU_INFO VALUES(101,'RAJU','CE');
INSERT INTO STU_INFO VALUES(102,'AMIT','CE');
INSERT INTO STU_INFO VALUES(103,'SANJAY','ME');
INSERT INTO STU_INFO VALUES(104,'NEHA','EC');
INSERT INTO STU_INFO VALUES(105,'MEERA','EE');
INSERT INTO STU_INFO VALUES(106,'MAHESH','ME');

CREATE TABLE RESULT
(RNO INT,
 SPI DECIMAL(10,2));

INSERT INTO RESULT VALUES(101,8.8);
INSERT INTO RESULT VALUES(102,9.2);
INSERT INTO RESULT VALUES(103,7.6);
INSERT INTO RESULT VALUES(104,8.2);
INSERT INTO RESULT VALUES(105,7.0);
INSERT INTO RESULT VALUES(106,8.9);

CREATE TABLE EMPLOYEE_MASTER
(EMPLOYEENO VARCHAR(10),
 NAME VARCHAR(20),
 MANAGERNO VARCHAR(10));

INSERT INTO EMPLOYEE_MASTER VALUES('E01','TARUN',NULL);
INSERT INTO EMPLOYEE_MASTER VALUES('E02','ROHAN','E02');
INSERT INTO EMPLOYEE_MASTER VALUES('E03','PRIYA','E01');
INSERT INTO EMPLOYEE_MASTER VALUES('E04','MILAN','E03');
INSERT INTO EMPLOYEE_MASTER VALUES('E05','JAY','E01');
INSERT INTO EMPLOYEE_MASTER VALUES('E06','ANJANA','E04');

--PART A
--1
SELECT * FROM STU_INFO CROSS JOIN RESULT;

--2
SELECT * FROM STU_INFO INNER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO;

--3
SELECT * FROM STU_INFO LEFT OUTER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO;

--4
SELECT * FROM STU_INFO RIGHT OUTER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO;

--5
SELECT * FROM STU_INFO FULL OUTER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO;

--6
SELECT STU_INFO.RNO,STU_INFO.BRANCH,STU_INFO.BRANCH,RESULT.SPI 
FROM STU_INFO JOIN RESULT 
ON STU_INFO.RNO=RESULT.RNO;

--7
SELECT STU_INFO.RNO,STU_INFO.BRANCH,STU_INFO.BRANCH,RESULT.SPI 
FROM STU_INFO JOIN RESULT 
ON STU_INFO.RNO=RESULT.RNO WHERE BRANCH='CE';

--8
SELECT STU_INFO.RNO,STU_INFO.BRANCH,STU_INFO.BRANCH,RESULT.SPI 
FROM STU_INFO JOIN RESULT 
ON STU_INFO.RNO=RESULT.RNO WHERE BRANCH<>'EC';

--9
SELECT STU_INFO.BRANCH,AVG(RESULT.SPI) 
FROM STU_INFO JOIN RESULT 
ON STU_INFO.RNO=RESULT.RNO GROUP BY BRANCH;

--10
SELECT STU_INFO.BRANCH,AVG(RESULT.SPI) 
FROM STU_INFO JOIN RESULT 
ON STU_INFO.RNO=RESULT.RNO 
GROUP BY BRANCH 
HAVING STU_INFO.BRANCH IN('CE','ME');

--PART B
--1
SELECT STU_INFO.BRANCH,AVG(RESULT.SPI) 
FROM STU_INFO JOIN RESULT 
ON STU_INFO.RNO=RESULT.RNO 
GROUP BY BRANCH 
ORDER BY BRANCH;

--2
SELECT STU_INFO.BRANCH,MAX(RESULT.SPI) 
FROM STU_INFO JOIN RESULT 
ON STU_INFO.RNO=RESULT.RNO 
GROUP BY BRANCH 
ORDER BY BRANCH DESC;

--PART C
--1
