--PART A

CREATE TABLE STUDENT(
STUID INT,
FIRSTNAME VARCHAR(25),
LASTNAME VARCHAR(25),
WEBSITE VARCHAR(50),
CITY VARCHAR(25),
ADDRESS VARCHAR(100));

INSERT INTO STUDENT VALUES(1011,'KEYUR','PATEL','techonthenet.com','RAJKOT','A-303 ‘Vasant Kunj’, Rajkot');
INSERT INTO STUDENT VALUES(1022,'HARDIK','SHAH','digminecraft.com','AHMEDABAD','“Ram Krupa”, Raiya Road');
INSERT INTO STUDENT VALUES(1033,'KAJAL','TRIVEDI','bigactivities.com','BARODA','Raj bhavan plot, near garden');
INSERT INTO STUDENT VALUES(1044,'BHOOMI','GAJERA','checkyourmath.com','AHMEDABAD','“Jig’s Home”, Narol');
INSERT INTO STUDENT VALUES(1055,'HARMIT','MITEL','@me.darshan.com','RAJKOT','B-55, Raj Residency');
INSERT INTO STUDENT VALUES(1066,'ASHOK','JANI',NULL,'BARODA','A502, Club House Building');

--1
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'K%';
--2
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____';
--3
SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE CITY LIKE 'A%' AND CITY LIKE '______';
--4
SELECT * FROM STUDENT WHERE LASTNAME LIKE '%TEL';
--5
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'HA%' AND FIRSTNAME LIKE '%T';
--6
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'K%' AND FIRSTNAME LIKE '__Y%';
--7
SELECT * FROM STUDENT WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____';
--8
SELECT * FROM STUDENT WHERE LASTNAME LIKE '%JER%';
--9
SELECT * FROM STUDENT WHERE CITY LIKE 'R%' OR CITY LIKE 'B%';
--10
SELECT * FROM STUDENT WHERE WEBSITE IS NOT NULL;
--11
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'A-H%';
--12
